### ISSUE TITLE
Good Work

### ISSUE THREAD

**Issue by AndreZila01** [HugoBatista/HTML--1#1]
Para primeiro projeto _HTML_ e _CSS_ não está mau. É continuar a trabalhar para ficar [TOP](https://media.giphy.com/media/l3q2LH45XElELRzRm/giphy.gif)

**Comment by HugoBatista** [comment]
Obgd ainda n ta nd acabado quero fazer melhorias como é obvio, já fiz melhor é apenas um exemplo

**Comment by AndreZila01** [comment]
Se precisares de ajuda, na parte do codificação (independentemente da linguagem), apita no discord.

**Comment by HugoBatista** [comment]
Obgd qualquer coisa eu aviso te sim
